2024-01-14 22:03:55,690 ERROR: Exception on /user/john/popup [GET] [in c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fmatl\Documents\FlaskMicroblog\app\main\routes.py", line 176, in user_popup
    return render_template('user_popup.html', user=user, form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\fmatl\Documents\FlaskMicroblog\app\templates\user_popup.html", line 9, in top-level template code
    <p>{{ _('%(count)d followers', count=user.followers.count()) }}, {{ _('%(count)d following', count=user.following.count()) }}</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\jinja2\utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'sqlalchemy.orm.writeonly.WriteOnlyCollection object' has no attribute 'count'
2024-01-14 22:05:49,326 INFO: Microblog startup [in C:\Users\fmatl\Documents\FlaskMicroblog\app\__init__.py:79]
2024-01-15 22:00:39,018 INFO: Microblog startup [in C:\Users\fmatl\Documents\FlaskMicroblog\app\__init__.py:79]
2024-01-15 22:00:54,349 INFO: Microblog startup [in C:\Users\fmatl\Documents\FlaskMicroblog\app\__init__.py:79]
2024-01-15 22:08:15,512 INFO: Microblog startup [in C:\Users\fmatl\Documents\FlaskMicroblog\app\__init__.py:79]
2024-01-15 22:10:04,476 INFO: Microblog startup [in C:\Users\fmatl\Documents\FlaskMicroblog\app\__init__.py:79]
2024-01-15 22:18:58,674 INFO: Microblog startup [in C:\Users\fmatl\Documents\FlaskMicroblog\app\__init__.py:79]
2024-01-15 22:19:02,835 INFO: Microblog startup [in C:\Users\fmatl\Documents\FlaskMicroblog\app\__init__.py:79]
2024-01-15 22:28:10,473 INFO: Microblog startup [in C:\Users\fmatl\Documents\FlaskMicroblog\app\__init__.py:79]
2024-01-15 22:28:26,842 ERROR: Exception on /send_message/john [GET] [in c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fmatl\Documents\FlaskMicroblog\app\main\routes.py", line 195, in send_message
    return render_template('send_message.html', title=_('Send Message'),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\fmatl\Documents\FlaskMicroblog\app\templates\send_message.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2024-01-15 22:32:31,226 INFO: Microblog startup [in C:\Users\fmatl\Documents\FlaskMicroblog\app\__init__.py:79]
2024-01-15 22:32:33,826 ERROR: Exception on /send_message/john [GET] [in c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fmatl\Documents\FlaskMicroblog\app\main\routes.py", line 195, in send_message
    return render_template('send_message.html', title=_('Send Message'),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\fmatl\Documents\FlaskMicroblog\app\templates\send_message.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\fmatl\Documents\FlaskMicroblog\.venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
